markdown: kramdown
pygments: true
paginate: 10
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
safe: false
embedly:
  api_key: 2f00b22bc6a345cca1775594796280ea